-----TÌM KIẾM SẢN PHẨM
IF OBJECT_ID('SP_TIMKIEM_SP') IS NOT NULL
	DROP PROC SP_TIMKIEM_SP
GO
CREATE PROC SP_TIMKIEM_SP
	@TENSP  NVARCHAR(50),
	@IDLSP INT,
	@TRANGTHAI  BIT,
	@TYPE VARCHAR(30)
AS
BEGIN
	IF (@TYPE = 'KW')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE TENSP LIKE '%' + @TENSP + '%'
    END
	IF (@TYPE = 'ID')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE IDLSP = @IDLSP
    END
	IF (@TYPE = 'TT')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE TRANGTHAI = @TRANGTHAI
    END
	IF (@TYPE = 'KW_ID')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE TENSP LIKE '%' + @TENSP + '%' AND IDLSP = @IDLSP
    END
	IF (@TYPE = 'KW_TT')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE TENSP LIKE '%' + @TENSP + '%' AND TRANGTHAI = @TRANGTHAI
    END
	IF (@TYPE = 'ID_TT')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE IDLSP = @IDLSP AND TRANGTHAI = @TRANGTHAI
    END
	ELSE IF (@TYPE = 'KW_ID_TT')
    BEGIN
        SELECT *
        FROM SANPHAM
		WHERE TENSP LIKE '%' + @TENSP + '%' AND IDLSP = @IDLSP AND TRANGTHAI = @TRANGTHAI
    END
END

-----TÌM KIẾM NGƯỜI DÙNG
GO 
IF OBJECT_ID('SP_TIMKIEM_ND') IS NOT NULL
	DROP PROC SP_TIMKIEM_ND
GO
CREATE PROC SP_TIMKIEM_ND
	@HOTEN  NVARCHAR(50),
	@IDVT INT,
	@TRANGTHAI  BIT,
	@TYPE VARCHAR(30)
AS
BEGIN
	IF (@TYPE = 'KW')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE HOTEN LIKE '%' + @HOTEN + '%'
    END
	IF (@TYPE = 'VT')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE IDVT = @IDVT
    END
	IF (@TYPE = 'TT')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE TRANGTHAI = @TRANGTHAI
    END
	IF (@TYPE = 'KW_VT')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE HOTEN LIKE '%' + @HOTEN + '%' AND IDVT = @IDVT
    END
	IF (@TYPE = 'KW_TT')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE HOTEN LIKE '%' + @HOTEN + '%' AND TRANGTHAI = @TRANGTHAI
    END
	IF (@TYPE = 'VT_TT')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE IDVT = @IDVT AND TRANGTHAI = @TRANGTHAI
    END
	ELSE IF (@TYPE = 'KW_VT_TT')
    BEGIN
        SELECT *
        FROM NGUOIDUNG
		WHERE HOTEN LIKE '%' + @HOTEN + '%' AND IDVT = @IDVT AND TRANGTHAI = @TRANGTHAI
    END
END

-----TÌM KIẾM KHUYẾN MẠI
GO 
IF OBJECT_ID('SP_TIMKIEM_KM') IS NOT NULL
	DROP PROC SP_TIMKIEM_KM
GO
CREATE PROC SP_TIMKIEM_KM
	@TENKM  NVARCHAR(50),
	@LOAIKM  BIT,
	@TRANGTHAI  BIT,
	@TYPE VARCHAR(30)
AS
BEGIN
	IF (@TYPE = 'KW')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE TENKM LIKE '%' + @TENKM + '%'
    END
	IF (@TYPE = 'LKM')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE LOAIKM = @LOAIKM
    END
	IF (@TYPE = 'TT')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE TRANGTHAI = @TRANGTHAI
    END
	IF (@TYPE = 'KW_LKM')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE TENKM LIKE '%' + @TENKM + '%' AND LOAIKM = @LOAIKM
    END
	IF (@TYPE = 'KW_TT')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE TENKM LIKE '%' + @TENKM + '%' AND TRANGTHAI = @TRANGTHAI
    END
	IF (@TYPE = 'LKM_TT')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE LOAIKM = @LOAIKM AND TRANGTHAI = @TRANGTHAI
    END
	ELSE IF (@TYPE = 'KW_LKM_TT')
    BEGIN
        SELECT *
        FROM KHUYENMAI
		WHERE TENKM LIKE '%' + @TENKM + '%' AND LOAIKM = @LOAIKM AND TRANGTHAI = @TRANGTHAI
    END
END

-----TÌM KIẾM HOÁ ĐƠN
GO
IF OBJECT_ID('SP_TIMKIEM_HD') IS NOT NULL
	DROP PROC SP_TIMKIEM_HD
GO
CREATE PROC SP_TIMKIEM_HD
	@TT1 INT,
	@TT2 INT,
    @TT3 INT, 
	@THOIGIAN1  DATE,
	@THOIGIAN2  DATE,
	@TYPE VARCHAR(30)
AS
BEGIN
	IF (@TYPE = 'TT') 
    BEGIN
        SELECT *
        FROM HOADON
		WHERE TRANGTHAI = @TT1
	END
	ELSE IF (@TYPE = 'TT1_TT2') 
    BEGIN
        SELECT *
        FROM HOADON
		WHERE TRANGTHAI = @TT1 OR TRANGTHAI = @TT2
	END
	ELSE  IF (@TYPE = 'TT023') 
    BEGIN
        SELECT *
        FROM HOADON
		WHERE TRANGTHAI = @TT1 OR TRANGTHAI = @TT2 OR TRANGTHAI = @TT3
	END
	ELSE IF (@TYPE = 'TT1_TG1_TG2')
    BEGIN
        SELECT *
        FROM HOADON
		WHERE TRANGTHAI = @TT1 AND TGTAO BETWEEN @THOIGIAN1 AND @THOIGIAN2
	END
	ELSE IF (@TYPE = 'TG1_TG2')
    BEGIN
        SELECT *
        FROM HOADON
		WHERE TGTAO BETWEEN @THOIGIAN1 AND @THOIGIAN2 OR TGTHANHTOAN BETWEEN @THOIGIAN1 AND @THOIGIAN2
	END
	ELSE
	BEGIN
		SELECT *
        FROM HOADON
	END
END

-----TÌM KIẾM HOÁ ĐƠN CHI TIẾT
GO
IF OBJECT_ID('SP_TIMKIEM_HDCT') IS NOT NULL
	DROP PROC SP_TIMKIEM_HDCT
GO
CREATE PROC SP_TIMKIEM_HDCT
    @IDHD INT,
	@TRANGTHAI BIT
AS
BEGIN
	IF (@TRANGTHAI IS NOT NULL) 
    BEGIN
        SELECT * 
        FROM HDCHITIET 
        WHERE IDHD=@IDHD AND TRANGTHAI = @TRANGTHAI
	END
	ELSE
	BEGIN
		SELECT * 
        FROM HDCHITIET 
        WHERE IDHD=@IDHD
	END
END
-----TÌM KIẾM ÁP DỤNG KM
GO
IF OBJECT_ID('SP_TIMKIEM_ADKM') IS NOT NULL
	DROP PROC SP_TIMKIEM_ADKM
GO
CREATE PROC SP_TIMKIEM_ADKM
	@IDKM  INT,
	@IDSP  INT,
	@TYPE VARCHAR(30)
AS
BEGIN
	IF (@TYPE = 'KM')
    BEGIN
        SELECT *
        FROM APDUNGKM
		WHERE IDKM = @IDKM
	END
	ELSE IF (@TYPE = 'SP')
    BEGIN
        SELECT *
        FROM APDUNGKM
		WHERE IDSP = @IDSP
	END
	ELSE IF (@TYPE = 'KM_SP')
    BEGIN
        SELECT *
        FROM APDUNGKM
		WHERE IDKM = @IDKM AND IDSP = @IDSP
	END
	ELSE
	BEGIN
		SELECT *
        FROM APDUNGKM
	END
END

-----TÌM KIẾM GIAO CA
GO
IF OBJECT_ID('SP_TIMKIEM_GC') IS NOT NULL
	DROP PROC SP_TIMKIEM_GC
GO
CREATE PROC SP_TIMKIEM_GC
	@DATE1  DATE,
	@DATE2  DATE,
	@TYPE VARCHAR(30)
AS
BEGIN
	IF (@TYPE = 'TYPE1')
    BEGIN
        SELECT *
        FROM GIAOCA
		WHERE TGBATDAU BETWEEN @DATE1 AND @DATE2 OR TGKETTHUC BETWEEN @DATE1 AND @DATE2
	END
	ELSE IF (@TYPE = 'TYPE2')
    BEGIN
        SELECT *
        FROM GIAOCA
		WHERE TGBATDAU BETWEEN @DATE1 AND @DATE2 OR TGKETTHUC BETWEEN @DATE1 AND @DATE2
        ORDER BY TGBATDAU DESC
	END
	ELSE
	BEGIN
		SELECT *
        FROM GIAOCA
        ORDER BY TGBATDAU DESC
	END
END
-----THỐNG KÊ DOANH THU
GO
IF OBJECT_ID('SP_TKDT') IS NOT NULL
	DROP PROC SP_TKDT
GO
CREATE PROC SP_TKDT
    @FROMDATE DATE,
    @TODATE DATE
AS
BEGIN
    SELECT 
        FORMAT(SUM(TONGTIEN), 'C0', 'vi-VN') AS TONG_TIEN,
        (SELECT COUNT(MAHD) FROM HOADON WHERE TRANGTHAI=4 AND TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE) AS HD_BAN,
        (SELECT COUNT(MAHD) FROM HOADON WHERE TRANGTHAI=4 AND DIACHI IS NOT NULL AND TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE) AS HD_GIAO,
        (SELECT COUNT(MAHD) FROM HOADON WHERE TRANGTHAI=5 AND TGTAO BETWEEN @FROMDATE AND @TODATE) AS HD_HUY
    FROM HOADON 
    WHERE TRANGTHAI=4 AND TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE
END
-----THỐNG KÊ SẢN PHẨM
GO
IF OBJECT_ID('SP_TKSP') IS NOT NULL
	DROP PROC SP_TKSP
GO
CREATE PROC SP_TKSP
    @FROMDATE DATE,
    @TODATE DATE,
    @IDLSP INT,
    @TRANGTHAI BIT
AS
BEGIN
    IF (@IDLSP IS NOT NULL AND @TRANGTHAI IS NOT NULL)
    BEGIN
        SELECT 
            MASP,
            TENSP,
            SUM(SOLUONG) AS SL,
            SANPHAM.TRANGTHAI
        FROM SANPHAM 
            JOIN HDCHITIET ON SANPHAM.ID=HDCHITIET.IDSP
            JOIN HOADON ON HDCHITIET.IDHD=HOADON.ID
        WHERE IDLSP=@IDLSP AND SANPHAM.TRANGTHAI=@TRANGTHAI AND TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE AND HOADON.TRANGTHAI=4
        GROUP BY MASP, TENSP, SANPHAM.TRANGTHAI
        ORDER BY SL DESC
	END
    ELSE IF (@IDLSP IS NOT NULL AND @FROMDATE IS NOT NULL AND @TODATE IS NOT NULL)
    BEGIN
        SELECT 
            MASP,
            TENSP,
            SUM(SOLUONG) AS SL,
            SANPHAM.TRANGTHAI
        FROM SANPHAM 
            JOIN HDCHITIET ON SANPHAM.ID=HDCHITIET.IDSP
            JOIN HOADON ON HDCHITIET.IDHD=HOADON.ID
        WHERE IDLSP=@IDLSP AND TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE AND HOADON.TRANGTHAI=4
        GROUP BY MASP, TENSP, SANPHAM.TRANGTHAI
        ORDER BY SL DESC
    END
    ELSE IF (@TRANGTHAI IS NOT NULL AND @FROMDATE IS NOT NULL AND @TODATE IS NOT NULL)
    BEGIN
        SELECT 
            MASP,
            TENSP,
            SUM(SOLUONG) AS SL,
            SANPHAM.TRANGTHAI
        FROM SANPHAM 
            JOIN HDCHITIET ON SANPHAM.ID=HDCHITIET.IDSP
            JOIN HOADON ON HDCHITIET.IDHD=HOADON.ID
        WHERE SANPHAM.TRANGTHAI=@TRANGTHAI AND TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE AND HOADON.TRANGTHAI=4
        GROUP BY MASP, TENSP, SANPHAM.TRANGTHAI
        ORDER BY SL DESC
	END
    ELSE IF (@FROMDATE IS NOT NULL AND @TODATE IS NOT NULL)
    BEGIN
        SELECT 
            MASP,
            TENSP,
            SUM(SOLUONG) AS SL,
            SANPHAM.TRANGTHAI
        FROM SANPHAM 
            JOIN HDCHITIET ON SANPHAM.ID=HDCHITIET.IDSP
            JOIN HOADON ON HDCHITIET.IDHD=HOADON.ID
        WHERE TGTHANHTOAN BETWEEN @FROMDATE AND @TODATE AND HOADON.TRANGTHAI=4
        GROUP BY MASP, TENSP, SANPHAM.TRANGTHAI
        ORDER BY SL DESC
	END
    ELSE
    BEGIN
        SELECT 
            MASP,
            TENSP,
            SUM(SOLUONG) AS SL,
            SANPHAM.TRANGTHAI
        FROM SANPHAM 
            JOIN HDCHITIET ON SANPHAM.ID=HDCHITIET.IDSP
            JOIN HOADON ON HDCHITIET.IDHD=HOADON.ID
        WHERE HOADON.TRANGTHAI=4
        GROUP BY MASP, TENSP, SANPHAM.TRANGTHAI
        ORDER BY SL DESC
	END
END