CREATE DATABASE QLCF
GO
USE QLCF 
GO
-----
-----BẢNG VAI TRÒ
-----
IF OBJECT_ID('AUTO_MAVT') IS NOT NULL
	DROP FUNCTION AUTO_MAVT
GO
CREATE FUNCTION AUTO_MAVT()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM VAITRO) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM VAITRO
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'VT00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'VT0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'VT' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('VAITRO') IS NOT NULL
	DROP TABLE VAITRO
GO
CREATE TABLE VAITRO
(
	ID INT IDENTITY(1,1) NOT NULL,
	MAVT VARCHAR(10) CONSTRAINT MAVT DEFAULT DBO.AUTO_MAVT(),
	TENVT NVARCHAR(50) NULL,
	CONSTRAINT PK_VAITRO PRIMARY KEY(ID)
)
GO
INSERT INTO [DBO].[VAITRO] ([TENVT]) VALUES (N'Quản lí')
INSERT INTO [DBO].[VAITRO] ([TENVT]) VALUES (N'Thu ngân')
INSERT INTO [DBO].[VAITRO] ([TENVT]) VALUES (N'Pha chế')
GO
SELECT * FROM VAITRO
-----
-----BẢNG NGƯỜI DÙNG
-----
GO
IF OBJECT_ID('AUTO_MAND') IS NOT NULL
	DROP FUNCTION AUTO_MAND
GO
CREATE FUNCTION AUTO_MAND()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM NGUOIDUNG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM NGUOIDUNG
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'ND00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'ND0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'ND' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('NGUOIDUNG') IS NOT NULL
	DROP TABLE NGUOIDUNG
GO
CREATE TABLE NGUOIDUNG
(
	ID INT IDENTITY(1,1) NOT NULL,
	MAND VARCHAR(10) CONSTRAINT MAND DEFAULT DBO.AUTO_MAND(),
	MATKHAU VARCHAR(50) NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NULL,
	GIOITINH BIT NULL,
	EMAIL VARCHAR(50) NULL,
	SDT VARCHAR(15) NULL,
	DIACHI NVARCHAR(150) NULL,
	IDVT INT NULL,
	GHICHU NVARCHAR(MAX) NULL,
	HINH NVARCHAR(150) NULL,
	TRANGTHAI BIT NULL,
	CONSTRAINT PK_NGUOIDUNG PRIMARY KEY(ID),
	CONSTRAINT FK_VAITRO_NGUOIDUNG FOREIGN KEY(IDVT) REFERENCES VAITRO
)
GO
-- Pass chưa mã hoá 123456
INSERT INTO [DBO].[NGUOIDUNG] ([MATKHAU],[HOTEN],[NGAYSINH],[GIOITINH],[EMAIL],[SDT],[DIACHI],[IDVT],[GHICHU],[HINH],[TRANGTHAI]) 
					VALUES ('e10adc3949ba59abbe56e057f20f883e', N'Nguyễn Thành Nam', '01/01/1999', 1, 'namntph18518@fpt.edu.vn', '0913480990', N'Hà Lội', 1, NULL, NULL, 1)
INSERT INTO [DBO].[NGUOIDUNG] ([MATKHAU],[HOTEN],[NGAYSINH],[GIOITINH],[EMAIL],[SDT],[DIACHI],[IDVT],[GHICHU],[HINH],[TRANGTHAI]) 
					VALUES ('e10adc3949ba59abbe56e057f20f883e', N'Vũ Văn Luân', '01/01/1999', 1, 'luanvvph18485@fpt.edu.vn', '0913480990', N'Hà Lội', 2, N'Fulltime', NULL, 1)
INSERT INTO [DBO].[NGUOIDUNG] ([MATKHAU],[HOTEN],[NGAYSINH],[GIOITINH],[EMAIL],[SDT],[DIACHI],[IDVT],[GHICHU],[HINH],[TRANGTHAI]) 
					VALUES ('e10adc3949ba59abbe56e057f20f883e', N'Lương Hoàng Tấn Minh', '01/01/1999', 1, 'minhlhtph18449@fpt.edu.vn', '0913480990', N'Hà Lội', 2, N'Parttime', NULL, 1)
INSERT INTO [DBO].[NGUOIDUNG] ([MATKHAU],[HOTEN],[NGAYSINH],[GIOITINH],[EMAIL],[SDT],[DIACHI],[IDVT],[GHICHU],[HINH],[TRANGTHAI]) 
					VALUES ('e10adc3949ba59abbe56e057f20f883e', N'Nguyễn Văn Việt', '01/01/1999', 1, 'vietnvph18432@fpt.edu.vn', '0913480990', N'Hà Lội', 3, N'Parttime', NULL, 1)
INSERT INTO [DBO].[NGUOIDUNG] ([MATKHAU],[HOTEN],[NGAYSINH],[GIOITINH],[EMAIL],[SDT],[DIACHI],[IDVT],[GHICHU],[HINH],[TRANGTHAI]) 
					VALUES ('e10adc3949ba59abbe56e057f20f883e', N'Đặng Ngọc Ánh', '01/01/1999', 0, 'anhdnph16882@fpt.edu.vn', '0913480990', N'Hà Lội', 3, N'Partime', NULL, 1)
INSERT INTO [DBO].[NGUOIDUNG] ([MATKHAU],[HOTEN],[NGAYSINH],[GIOITINH],[EMAIL],[SDT],[DIACHI],[IDVT],[GHICHU],[HINH],[TRANGTHAI]) 
					VALUES ('e10adc3949ba59abbe56e057f20f883e', N'Nguyễn Phi Hùng', '01/01/1999', 1, 'hungnpph24034@fpt.edu.vn', '0913480990', N'Hà Lội', 2, N'Parttime', NULL, 1)
GO
SELECT * FROM NGUOIDUNG
-----
-----BẢNG GIAO CA
-----
GO
IF OBJECT_ID('AUTO_MAGC') IS NOT NULL
	DROP FUNCTION AUTO_MAGC
GO
CREATE FUNCTION AUTO_MAGC()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM GIAOCA) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM GIAOCA
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CA00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CA0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'CA' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('GIAOCA') IS NOT NULL
	DROP TABLE GIAOCA
GO
CREATE TABLE GIAOCA
(
	ID INT IDENTITY(1,1) NOT NULL,
	MACA VARCHAR(10) CONSTRAINT MACA DEFAULT DBO.AUTO_MAGC(),
	IDND INT NULL,
	TGBATDAU DATETIME NULL,
	TGKETTHUC DATETIME NULL,
	TIENBANDAU MONEY NULL,
	DOANHTHU MONEY NULL,
	TIENCK MONEY NULL,
	TIENMAT MONEY NULL,
	TONGTIENCA MONEY NULL,
	TIENCHUTHU MONEY NULL,
	TIENPHATSINH MONEY NULL,
	GHICHU NVARCHAR(MAX) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT PK_GIAOCA PRIMARY KEY(ID),
	CONSTRAINT FK_NGUOIDUNG_GIAOCA FOREIGN KEY(IDND) REFERENCES NGUOIDUNG
)
-----
-----BẢNG KHÁCH HÀNG
-----
GO
IF OBJECT_ID('AUTO_MAKH') IS NOT NULL
	DROP FUNCTION AUTO_MAKH
GO
CREATE FUNCTION AUTO_MAKH()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM KHACHHANG
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'KH' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('KHACHHANG') IS NOT NULL
	DROP TABLE KHACHHANG
GO
CREATE TABLE KHACHHANG
(
	ID INT IDENTITY(1,1) NOT NULL,
	MAKH VARCHAR(10) CONSTRAINT MAKH DEFAULT DBO.AUTO_MAKH(),
	HOTEN NVARCHAR(50) NULL,
	SDT VARCHAR(15) NULL,
	DIACHI NVARCHAR(150) NULL,
	DIEM INT NULL,
	TRANGTHAI BIT NULL,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(ID)
)
GO
INSERT INTO [DBO].[KHACHHANG] ([HOTEN],[SDT],[DIACHI],[DIEM],[TRANGTHAI]) VALUES (N'Nguyễn Anh Dũng', '0987654321', N'Bí mật', 0, 1)
GO
SELECT * FROM KHACHHANG
-----
-----BẢNG LOẠI THANH TOÁN
-----
GO
IF OBJECT_ID('LOAITHANHTOAN') IS NOT NULL
	DROP TABLE LOAITHANHTOAN
GO
CREATE TABLE LOAITHANHTOAN
(
	MALTT VARCHAR(10) NOT NULL,
	TENLTT NVARCHAR(50) NULL,
	CONSTRAINT PK_LOAITHANHTOAN PRIMARY KEY(MALTT)
)
GO
INSERT INTO [DBO].[LOAITHANHTOAN] ([MALTT],[TENLTT]) VALUES ('LTT001',N'Tiền mặt')
INSERT INTO [DBO].[LOAITHANHTOAN] ([MALTT],[TENLTT]) VALUES ('LTT002',N'Chuyển khoản')
GO
SELECT * FROM LOAITHANHTOAN
-----
-----BẢNG LOẠI SẢN PHẨM
-----
GO
IF OBJECT_ID('AUTO_MALSP') IS NOT NULL
	DROP FUNCTION AUTO_MALSP
GO
CREATE FUNCTION AUTO_MALSP()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM LOAISANPHAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM LOAISANPHAM
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'LSP00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'LSP0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'LSP' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('LOAISANPHAM') IS NOT NULL
	DROP TABLE LOAISANPHAM
GO
CREATE TABLE LOAISANPHAM
(
	ID INT IDENTITY(1,1) NOT NULL,
	MALSP VARCHAR(10) CONSTRAINT MALSP DEFAULT DBO.AUTO_MALSP(),
	TENLSP NVARCHAR(50) NULL,
	CONSTRAINT PK_LOAISANPHAM PRIMARY KEY(ID)
)
GO
INSERT INTO [DBO].[LOAISANPHAM] ([TENLSP]) VALUES (N'Cà phê')
INSERT INTO [DBO].[LOAISANPHAM] ([TENLSP]) VALUES (N'Trà trái cây - Trà Sữa')
INSERT INTO [DBO].[LOAISANPHAM] ([TENLSP]) VALUES (N'Đá xay - Choco - Matcha')
INSERT INTO [DBO].[LOAISANPHAM] ([TENLSP]) VALUES (N'Bánh - Snack')
GO
SELECT * FROM LOAISANPHAM
-----
-----BẢNG SẢN PHẨM
-----
GO
IF OBJECT_ID('AUTO_MASP') IS NOT NULL
	DROP FUNCTION AUTO_MASP
GO
CREATE FUNCTION AUTO_MASP()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM SANPHAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM SANPHAM
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'SP00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'SP0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'SP' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('SANPHAM') IS NOT NULL
	DROP TABLE SANPHAM
GO
CREATE TABLE SANPHAM
(
	ID INT IDENTITY(1,1) NOT NULL,
	MASP VARCHAR(10) CONSTRAINT MASP DEFAULT DBO.AUTO_MASP(),
	TENSP NVARCHAR(50) NULL,
	IDLSP INT NOT NULL,
	DONGIA MONEY NULL,
	HINH NVARCHAR(50) NULL,
	MOTA NVARCHAR(MAX) NULL,
	GHICHU NVARCHAR(MAX) NULL,
	TRANGTHAI BIT NULL,
	CONSTRAINT PK_SANPHAM PRIMARY KEY(ID),
	CONSTRAINT FK_SANPHAM_LOAISANPHAM FOREIGN KEY(IDLSP) REFERENCES LOAISANPHAM
)
GO
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Cà Phê Đen Đá', 1, 35000, 'SP001.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Cà Phê Sữa Đá', 1, 35000, 'SP002.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Bạc Sỉu', 1, 29000, 'SP003.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Caramel Macchiato', 1, 54000, 'SP004.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Cappuccino', 1, 54000, 'SP005.jpg', N'Không', N'Món mới', 0)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Trà Đào Cam Sả', 2, 51000, 'SP006.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Trà Hạt Sen', 2, 51000, 'SP007.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Trà Đen Macchiato', 2, 49000, 'SP008.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI])  
										VALUES (N'Hồng Trà Sữa', 2, 54000, 'SP009.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Trà Sữa Mắc Ca Trân Châu', 2, 49000, 'SP010.jpg', N'Không', N'Không', 0)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI])  
										VALUES (N'Trà Long Nhãn Hạt Chia', 2, 49000, 'SP011.jpg', N'Không', N'Món mới', 0)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Cookie Đá Say', 3, 58000, 'SP012.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Chocolate Đá Say', 3, 58000, 'SP013.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI])  
										VALUES (N'Matcha Đá Say', 3, 58000, 'SP014.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Chocolate', 3, 58000, 'SP015.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Trà Matcha Latte', 3, 58000, 'SP016.jpg', N'Không', N'Món mới', 0)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Bánh Mì Que Pate', 4, 12000, 'SP017.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Bánh Mì VN Thịt Nguội', 4, 15000, 'SP018.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Mochi Kem Việt Quất', 4, 19000, 'SP019.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Mochi Gấu Chocolate', 4, 39000, 'SP020.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI]) 
										VALUES (N'Mousse Tiramisu', 4, 32000, 'SP021.jpg', N'Không', N'Không', 1)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI])  
										VALUES (N'Mousse Red Velvet', 4, 29000, 'SP022.jpg', N'Không', N'Không', 0)
INSERT INTO [DBO].[SANPHAM] ([TENSP],[IDLSP],[DONGIA],[HINH],[MOTA],[GHICHU],[TRANGTHAI])  
										VALUES (N'Hướng Dương', 4, 10000, 'NULL', N'Không', N'Không', 0)
GO
SELECT * FROM SANPHAM
-----
-----BANG KHUYEN MAI
-----
GO
IF OBJECT_ID('AUTO_MAKM') IS NOT NULL
	DROP FUNCTION AUTO_MAKM
GO
CREATE FUNCTION AUTO_MAKM()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM KHUYENMAI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM KHUYENMAI
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KM00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KM0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'KM' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('KHUYENMAI') IS NOT NULL
	DROP TABLE KHUYENMAI
GO
CREATE TABLE KHUYENMAI
(
	ID INT IDENTITY(1,1) NOT NULL,
	MAKM VARCHAR(10) CONSTRAINT MAKM DEFAULT DBO.AUTO_MAKM(),
	TENKM NVARCHAR(50) NULL,
	LOAIKM BIT NULL,
	GIATRIKM INT NULL,
	NGAYBD DATE NULL,
	NGAYKT DATE NULL,
	TRANGTHAI BIT NULL,
	CONSTRAINT PK_KHUYENMAI PRIMARY KEY(ID)
)
GO
INSERT INTO [DBO].[KHUYENMAI] ([TENKM],[LOAIKM],[GIATRIKM],[NGAYBD],[NGAYKT],[TRANGTHAI]) 
										VALUES (N'Quốc tế phụ nữ 8/3', 1, 20, '03/06/2022', '03/10/2022', 0)
INSERT INTO [DBO].[KHUYENMAI] ([TENKM],[LOAIKM],[GIATRIKM],[NGAYBD],[NGAYKT],[TRANGTHAI]) 
										VALUES (N'Tháng thanh niên', 0, 10000, '03/20/2022', '03/31/2022', 1)
INSERT INTO [DBO].[KHUYENMAI] ([TENKM],[LOAIKM],[GIATRIKM],[NGAYBD],[NGAYKT],[TRANGTHAI]) 
										VALUES (N'Bảo vệ dự án', 1, 30, '04/15/2022', '04/25/2022', 0)
GO
SELECT * FROM KHUYENMAI
-----
-----BẢNG ÁP DỤNG KM
-----
GO
IF OBJECT_ID('APDUNGKM') IS NOT NULL
	DROP TABLE APDUNGKM
GO
CREATE TABLE APDUNGKM
(
	IDKM INT NOT NULL,
	IDSP INT NOT NULL,
	CONSTRAINT FK_KHUYENMAI_APDUNGKM FOREIGN KEY(IDKM) REFERENCES KHUYENMAI,
	CONSTRAINT FK_SANPHAM_APDUNGKM FOREIGN KEY(IDSP) REFERENCES SANPHAM,
	CONSTRAINT PK_APDUNGKM PRIMARY KEY (IDKM, IDSP)
)
GO
INSERT INTO [DBO].[APDUNGKM] ([IDKM],[IDSP]) VALUES (3,1)
INSERT INTO [DBO].[APDUNGKM] ([IDKM],[IDSP]) VALUES (3,2)
INSERT INTO [DBO].[APDUNGKM] ([IDKM],[IDSP]) VALUES (3,3)
GO
SELECT * FROM APDUNGKM
-----
-----BẢNG HÓA ĐƠN
-----
GO
IF OBJECT_ID('AUTO_MAHD') IS NOT NULL
	DROP FUNCTION AUTO_MAHD
GO
CREATE FUNCTION AUTO_MAHD()
RETURNS VARCHAR(10)
AS
BEGIN
    DECLARE @ID VARCHAR(10)
    IF (SELECT COUNT(ID) FROM HOADON) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(ID) FROM HOADON
    SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 THEN 'HD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
    RETURN @ID
END
GO
IF OBJECT_ID('HOADON') IS NOT NULL
	DROP TABLE HOADON
GO
CREATE TABLE HOADON
(
	ID INT IDENTITY(1,1) NOT NULL,
	MAHD VARCHAR(10) CONSTRAINT MAHD DEFAULT DBO.AUTO_MAHD(),
	IDCA INT NULL,
	IDND INT NULL,
	IDKH INT NULL,
	TGTAO DATETIME NULL,
	TGTHANHTOAN DATETIME NULL,
	CHIPHIKHAC MONEY NULL,
	TONGTIEN MONEY NULL,
	DIACHI NVARCHAR(100) NULL,
	MALTT VARCHAR(10) NULL,
	GHICHU NVARCHAR(MAX) NULL,
	TRANGTHAI INT NULL,
	CONSTRAINT PK_HOADON PRIMARY KEY(ID),
	CONSTRAINT FK_GIAOCA_HOADON FOREIGN KEY(IDCA) REFERENCES GIAOCA,
	CONSTRAINT FK_NGUOIDUNG_HOADON FOREIGN KEY(IDND) REFERENCES NGUOIDUNG,
	CONSTRAINT FK_KHACHHANG_HOADON FOREIGN KEY(IDKH) REFERENCES KHACHHANG,
	CONSTRAINT FK_LOAITHANHTOAN_HOADON FOREIGN KEY(MALTT) REFERENCES LOAITHANHTOAN
)
-----
-----BẢNG HÓA ĐƠN CHI TIẾT
-----
GO
IF OBJECT_ID('HDCHITIET') IS NOT NULL
	DROP TABLE HDCHITIET
GO
CREATE TABLE HDCHITIET
(
	ID INT IDENTITY(1,1) NOT NULL,
	IDHD INT NOT NULL,
	IDSP INT NOT NULL,
	SOLUONG INT NULL,
	DONGIA MONEY NULL,
	GHICHU NVARCHAR(MAX) NULL,
	TRANGTHAI BIT NULL,
	CONSTRAINT FK_HOADON_HDCHITIET FOREIGN KEY(IDHD) REFERENCES HOADON,
	CONSTRAINT FK_SANPHAM_HDCHITIET FOREIGN KEY(IDSP) REFERENCES SANPHAM,
	CONSTRAINT PK_HDCHITIET PRIMARY KEY(ID)
)

-----
-----
-----

SELECT * FROM VAITRO
SELECT * FROM NGUOIDUNG
SELECT * FROM KHACHHANG
SELECT * FROM LOAITHANHTOAN
SELECT * FROM LOAISANPHAM
SELECT * FROM SANPHAM
SELECT * FROM KHUYENMAI
SELECT * FROM APDUNGKM
SELECT * FROM HOADON
SELECT * FROM HDCHITIET
SELECT * FROM GIAOCA

